from pathlib import Path
p=Path('index.html')
s=p.read_text()
if 'CJ24H-DOCTOR-WEB-PUSH-V1' in s:
    raise SystemExit('already patched')
css='''\n/* CJ24H-DOCTOR-WEB-PUSH-V1 */\n.cj-push-doctor{position:fixed;right:18px;bottom:18px;z-index:350;display:none;align-items:center;gap:12px;max-width:360px;padding:12px 13px;border-radius:14px;border:1px solid rgba(94,224,160,.16);background:rgba(8,17,14,.96);box-shadow:0 18px 50px rgba(0,0,0,.35);backdrop-filter:blur(14px)}.cj-push-doctor.show{display:flex}.cj-push-doctor__dot{width:9px;height:9px;border-radius:50%;background:#62c58a;box-shadow:0 0 0 5px rgba(98,197,138,.08);flex:0 0 auto}.cj-push-doctor__copy{min-width:0;flex:1}.cj-push-doctor__title{font-size:.78rem;font-weight:650;color:#f2f6f4}.cj-push-doctor__sub{font-size:.68rem;line-height:1.4;color:rgba(231,235,233,.48);margin-top:2px}.cj-push-doctor button{border:1px solid rgba(94,224,160,.2);background:rgba(94,224,160,.08);color:#8bd8aa;border-radius:9px;padding:8px 10px;font:600 .68rem Inter,sans-serif;cursor:pointer;white-space:nowrap}@media(max-width:560px){.cj-push-doctor{left:12px;right:12px;bottom:12px;max-width:none}}\n'''
s=s.replace('</style>',css+'\n</style>',1)
js=r'''\n// CJ24H-DOCTOR-WEB-PUSH-V1\nvar cjDocPushBusy=false;\nfunction cjDocB64ToU8(v){var p='='.repeat((4-v.length%4)%4),b=(v+p).replace(/-/g,'+').replace(/_/g,'/'),r=atob(b),o=new Uint8Array(r.length);for(var i=0;i<r.length;i++)o[i]=r.charCodeAt(i);return o;}\nfunction cjDocPushBar(){var x=document.getElementById('cjPushDoctor');if(x)return x;x=document.createElement('div');x.id='cjPushDoctor';x.className='cj-push-doctor';x.innerHTML='<span class="cj-push-doctor__dot"></span><div class="cj-push-doctor__copy"><div class="cj-push-doctor__title">Mensagens do paciente em tempo real</div><div class="cj-push-doctor__sub">Receba um aviso mesmo com o painel em segundo plano.</div></div><button type="button" onclick="cjAtivarPushMedico()">Ativar</button>';document.body.appendChild(x);return x;}\nfunction cjDocPodePush(){return !!(window.isSecureContext&&'serviceWorker'in navigator&&'PushManager'in window&&'Notification'in window&&medico&&medico.id&&getToken());}\nfunction cjDocAtualizarPushUI(){var x=cjDocPushBar();if(!cjDocPodePush()){x.classList.remove('show');return}if(Notification.permission==='denied'){x.classList.remove('show');return}if(Notification.permission==='granted'){x.classList.remove('show');cjRegistrarPushMedico(false);return}x.classList.add('show');}\nasync function cjRegistrarPushMedico(pedir){if(cjDocPushBusy||!cjDocPodePush())return false;cjDocPushBusy=true;try{var perm=Notification.permission;if(perm==='default'&&pedir)perm=await Notification.requestPermission();if(perm!=='granted'){cjDocAtualizarPushUI();return false}var reg=await navigator.serviceWorker.register('/push-sw.js',{scope:'/'});var kd=await (await fetch(API+'/api/web-push/public-key')).json();if(!kd.ok||!kd.publicKey)throw new Error('push_indisponivel');var sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:cjDocB64ToU8(kd.publicKey)});var r=await fetch(API+'/api/web-push/chat-subscribe',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+getToken()},body:JSON.stringify({papel:'medico',medicoId:medico.id,subscription:sub.toJSON()})});var d=await r.json().catch(function(){return{}});if(!r.ok||!d.ok)throw new Error(d.error||'push_failed');cjDocPushBar().classList.remove('show');return true}catch(e){console.warn('[WEB-PUSH-MEDICO]',e);return false}finally{cjDocPushBusy=false}}\nfunction cjAtivarPushMedico(){cjRegistrarPushMedico(true)}window.cjAtivarPushMedico=cjAtivarPushMedico;\n(function(){setInterval(function(){try{if(document.body.classList.contains('app-autenticado')||getToken())cjDocAtualizarPushUI()}catch(e){}},2500)})();\n'''
pos=s.rfind('</script>')
if pos<0: raise SystemExit('script end not found')
s=s[:pos]+js+s[pos:]
p.write_text(s)
print('patched panel index.html')
